/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TournamentDto } from '../../models/tournament-dto';
import { UpdateTournamentRequest } from '../../models/update-tournament-request';

export interface ApiTournamentsIdPut$Params {
  id: string;
  body: UpdateTournamentRequest;
}

export function apiTournamentsIdPut(
  http: HttpClient,
  rootUrl: string,
  params: ApiTournamentsIdPut$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<TournamentDto>> {
  const rb = new RequestBuilder(rootUrl, apiTournamentsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TournamentDto>;
    }),
  );
}

apiTournamentsIdPut.PATH = '/api/tournaments/{id}';
