/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoundDto } from '../../models/round-dto';

export interface ApiTournamentsTournamentIdRoundsPost$Params {
  tournamentId: string;
}

export function apiTournamentsTournamentIdRoundsPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiTournamentsTournamentIdRoundsPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<RoundDto>> {
  const rb = new RequestBuilder(rootUrl, apiTournamentsTournamentIdRoundsPost.PATH, 'post');
  if (params) {
    rb.path('tournamentId', params.tournamentId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoundDto>;
    }),
  );
}

apiTournamentsTournamentIdRoundsPost.PATH = '/api/tournaments/{tournamentId}/rounds';
