/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoundDto } from '../../models/round-dto';

export interface ApiTournamentsIdRoundsGet$Params {
  id: string;
}

export function apiTournamentsIdRoundsGet(
  http: HttpClient,
  rootUrl: string,
  params: ApiTournamentsIdRoundsGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<RoundDto>>> {
  const rb = new RequestBuilder(rootUrl, apiTournamentsIdRoundsGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoundDto>>;
    }),
  );
}

apiTournamentsIdRoundsGet.PATH = '/api/tournaments/{id}/rounds';
