/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTournamentCommand } from '../../models/create-tournament-command';
import { TournamentDto } from '../../models/tournament-dto';

export interface ApiTournamentsPost$Params {
  body: CreateTournamentCommand;
}

export function apiTournamentsPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiTournamentsPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<TournamentDto>> {
  const rb = new RequestBuilder(rootUrl, apiTournamentsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TournamentDto>;
    }),
  );
}

apiTournamentsPost.PATH = '/api/tournaments';
