/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePlayerCommand } from '../../models/create-player-command';
import { PlayerDto } from '../../models/player-dto';

export interface ApiPlayersPost$Params {
  body: CreatePlayerCommand;
}

export function apiPlayersPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiPlayersPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PlayerDto>> {
  const rb = new RequestBuilder(rootUrl, apiPlayersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlayerDto>;
    }),
  );
}

apiPlayersPost.PATH = '/api/players';
