/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlayerDto } from '../../models/player-dto';

export interface ApiPlayersUserUserIdGet$Params {
  userId: string;
}

export function apiPlayersUserUserIdGet(
  http: HttpClient,
  rootUrl: string,
  params: ApiPlayersUserUserIdGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PlayerDto>> {
  const rb = new RequestBuilder(rootUrl, apiPlayersUserUserIdGet.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlayerDto>;
    }),
  );
}

apiPlayersUserUserIdGet.PATH = '/api/players/user/{userId}';
