/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlayerDto } from '../../models/player-dto';
import { UpdatePlayerProfileCommand } from '../../models/update-player-profile-command';

export interface ApiPlayersPlayerIdPut$Params {
  playerId: string;
  body: UpdatePlayerProfileCommand;
}

export function apiPlayersPlayerIdPut(
  http: HttpClient,
  rootUrl: string,
  params: ApiPlayersPlayerIdPut$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<PlayerDto>> {
  const rb = new RequestBuilder(rootUrl, apiPlayersPlayerIdPut.PATH, 'put');
  if (params) {
    rb.path('playerId', params.playerId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlayerDto>;
    }),
  );
}

apiPlayersPlayerIdPut.PATH = '/api/players/{playerId}';
