/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AchievementResponse } from '../../models/achievement-response';

export interface GetPlayerAchievements$Params {
  playerId: string;
}

export function getPlayerAchievements(
  http: HttpClient,
  rootUrl: string,
  params: GetPlayerAchievements$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<AchievementResponse>>> {
  const rb = new RequestBuilder(rootUrl, getPlayerAchievements.PATH, 'get');
  if (params) {
    rb.path('playerId', params.playerId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AchievementResponse>>;
    }),
  );
}

getPlayerAchievements.PATH = '/api/players/{playerId}/achievements';
