/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TournamentRequestDto } from '../../models/tournament-request-dto';

export interface ApiTournamentRequestsGet$Params {}

export function apiTournamentRequestsGet(
  http: HttpClient,
  rootUrl: string,
  params?: ApiTournamentRequestsGet$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<TournamentRequestDto>>> {
  const rb = new RequestBuilder(rootUrl, apiTournamentRequestsGet.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TournamentRequestDto>>;
    }),
  );
}

apiTournamentRequestsGet.PATH = '/api/tournament-requests';
