/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTournamentRequestCommand } from '../../models/create-tournament-request-command';
import { TournamentRequestDto } from '../../models/tournament-request-dto';

export interface ApiTournamentRequestsPost$Params {
  body: CreateTournamentRequestCommand;
}

export function apiTournamentRequestsPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiTournamentRequestsPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<TournamentRequestDto>> {
  const rb = new RequestBuilder(rootUrl, apiTournamentRequestsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TournamentRequestDto>;
    }),
  );
}

apiTournamentRequestsPost.PATH = '/api/tournament-requests';
