/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RejectTournamentRequestEndpointRejectRequest } from '../../models/reject-tournament-request-endpoint-reject-request';
import { TournamentRequestDto } from '../../models/tournament-request-dto';

export interface ApiTournamentRequestsRequestIdRejectPost$Params {
  requestId: string;
  body: RejectTournamentRequestEndpointRejectRequest;
}

export function apiTournamentRequestsRequestIdRejectPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiTournamentRequestsRequestIdRejectPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<TournamentRequestDto>> {
  const rb = new RequestBuilder(rootUrl, apiTournamentRequestsRequestIdRejectPost.PATH, 'post');
  if (params) {
    rb.path('requestId', params.requestId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TournamentRequestDto>;
    }),
  );
}

apiTournamentRequestsRequestIdRejectPost.PATH = '/api/tournament-requests/{requestId}/reject';
