/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TournamentRequestDto } from '../../models/tournament-request-dto';

export interface ApiTournamentRequestsRequestIdCancelPost$Params {
  requestId: string;
}

export function apiTournamentRequestsRequestIdCancelPost(
  http: HttpClient,
  rootUrl: string,
  params: ApiTournamentRequestsRequestIdCancelPost$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<TournamentRequestDto>> {
  const rb = new RequestBuilder(rootUrl, apiTournamentRequestsRequestIdCancelPost.PATH, 'post');
  if (params) {
    rb.path('requestId', params.requestId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TournamentRequestDto>;
    }),
  );
}

apiTournamentRequestsRequestIdCancelPost.PATH = '/api/tournament-requests/{requestId}/cancel';
