/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddMatchTagRequest } from '../../models/add-match-tag-request';

export interface AddMatchTag$Params {
  matchId: string;
  body: AddMatchTagRequest;
}

export function addMatchTag(
  http: HttpClient,
  rootUrl: string,
  params: AddMatchTag$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, addMatchTag.PATH, 'post');
  if (params) {
    rb.path('matchId', params.matchId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

addMatchTag.PATH = '/api/matches/{matchId}/tags';
