/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMatchRequest } from '../../models/create-match-request';
import { CreateMatchResponse } from '../../models/create-match-response';

export interface CreateMatch$Params {
  body: CreateMatchRequest;
}

export function createMatch(
  http: HttpClient,
  rootUrl: string,
  params: CreateMatch$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<CreateMatchResponse>> {
  const rb = new RequestBuilder(rootUrl, createMatch.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateMatchResponse>;
    }),
  );
}

createMatch.PATH = '/api/matches';
