/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TournamentMatchDto } from '../../models/tournament-match-dto';

export interface GetMatchById$Params {
  matchId: string;
}

export function getMatchById(
  http: HttpClient,
  rootUrl: string,
  params: GetMatchById$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<TournamentMatchDto>> {
  const rb = new RequestBuilder(rootUrl, getMatchById.PATH, 'get');
  if (params) {
    rb.path('matchId', params.matchId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TournamentMatchDto>;
    }),
  );
}

getMatchById.PATH = '/api/matches/{matchId}';
