/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface RemoveMatchTag$Params {
  matchId: string;
  tagName: string;
}

export function removeMatchTag(
  http: HttpClient,
  rootUrl: string,
  params: RemoveMatchTag$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, removeMatchTag.PATH, 'delete');
  if (params) {
    rb.path('matchId', params.matchId, {});
    rb.path('tagName', params.tagName, {});
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

removeMatchTag.PATH = '/api/matches/{matchId}/tags/{tagName}';
