/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TournamentMatchDto } from '../../models/tournament-match-dto';

export interface SearchMatches$Params {
  playerId?: string;
  tags?: string;
  tournamentId?: string;
  roundId?: string;
}

export function searchMatches(
  http: HttpClient,
  rootUrl: string,
  params?: SearchMatches$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<TournamentMatchDto>>> {
  const rb = new RequestBuilder(rootUrl, searchMatches.PATH, 'get');
  if (params) {
    rb.query('playerId', params.playerId, {});
    rb.query('tags', params.tags, {});
    rb.query('tournamentId', params.tournamentId, {});
    rb.query('roundId', params.roundId, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TournamentMatchDto>>;
    }),
  );
}

searchMatches.PATH = '/api/matches/search';
