/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateMatchMovesRequest } from '../../models/update-match-moves-request';

export interface UpdateMatchMoves$Params {
  matchId: string;
  body: UpdateMatchMovesRequest;
}

export function updateMatchMoves(
  http: HttpClient,
  rootUrl: string,
  params: UpdateMatchMoves$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, updateMatchMoves.PATH, 'put');
  if (params) {
    rb.path('matchId', params.matchId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'text', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    }),
  );
}

updateMatchMoves.PATH = '/api/matches/{matchId}/moves';
