/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AchievementResponse {
  achievedAt: string;
  id: string;
  medalEmoji: string;
  position: number | string;
  positionText: string;
  score: number | string;
  tournamentId: string;
  tournamentName: string;
}
