/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimeControl } from '../models/time-control';
import { TournamentFormat } from '../models/tournament-format';
export interface CreateTournamentCommand {
  allowByes: boolean;
  description: string;
  entryFee: number | string;
  format: TournamentFormat;
  incrementInSeconds: number | string;
  location: string;
  maxPlayers: number | string;
  minPlayers: number | string;
  name: string;
  numberOfRounds: number | string;
  organizerId: string;
  startDate: string;
  timeControl: TimeControl;
  timeInMinutes: number | string;
}
