/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMatchRequest {
  blackPlayerId: string;
  boardNumber: number | string;
  roundId: string;
  tournamentId: string;
  whitePlayerId: string;
}
