/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePlayerCommand {
  country?: string | null;
  dateOfBirth?: string | null;
  firstName: string;
  initialRating?: number | string;
  lastName: string;
  userId: string;
}
