/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameResult } from '../models/game-result';
export interface MatchDto {
  blackPlayerId?: string;
  boardNumber?: number | string;
  completedAt?: string | null;
  id?: string;
  isCompleted?: boolean;
  moves?: string | null;
  result?: GameResult;
  roundId?: string;
  tournamentId?: string;
  whitePlayerId?: string;
}
