/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlayerDto {
  avatarUrl?: string | null;
  bio?: string | null;
  country?: string | null;
  createdAt?: string;
  dateOfBirth?: string | null;
  drawRate?: number | string;
  draws?: number | string;
  firstName?: string;
  fullName?: string;
  id?: string;
  lastName?: string;
  lossRate?: number | string;
  losses?: number | string;
  peakRating?: number | string;
  peakRatingDate?: string | null;
  rating?: number | string;
  totalGamesPlayed?: number | string;
  tournamentsParticipated?: number | string;
  tournamentsWon?: number | string;
  updatedAt?: string | null;
  userId?: string;
  winRate?: number | string;
  wins?: number | string;
}
