/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MatchDto } from '../models/match-dto';
export interface RoundDto {
  endTime?: string | null;
  id?: string;
  isCompleted?: boolean;
  matchCount?: number | string;
  matches?: Array<MatchDto>;
  roundNumber?: number | string;
  startTime?: string | null;
  tournamentId?: string;
}
