/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameResult } from '../models/game-result';
import { MatchTagDto } from '../models/match-tag-dto';
export interface TournamentMatchDto {
  blackPlayerId?: string;
  boardNumber?: number | string;
  completedAt?: string | null;
  createdAt?: string;
  id?: string;
  isCompleted?: boolean;
  moves?: string | null;
  result?: GameResult;
  roundId?: string;
  scheduledTime?: string;
  tags?: Array<MatchTagDto>;
  tournamentId?: string;
  updatedAt?: string | null;
  whitePlayerId?: string;
}
