/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TournamentSettingsDto } from '../models/tournament-settings-dto';
import { TournamentStatus } from '../models/tournament-status';
export interface TournamentDto {
  createdAt?: string;
  description?: string;
  endDate?: string | null;
  id?: string;
  location?: string;
  name?: string;
  organizerId?: string;
  playerCount?: number | string;
  roundCount?: number | string;
  settings?: TournamentSettingsDto;
  startDate?: string;
  status?: TournamentStatus;
}
