/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RequestStatus } from '../models/request-status';
export interface TournamentRequestDto {
  createdAt?: string;
  id?: string;
  rejectionReason?: string | null;
  requestedBy?: string;
  reviewedAt?: string | null;
  reviewedBy?: string | null;
  status?: RequestStatus;
  tournamentId?: string;
}
