/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum TournamentStatus {
  Draft = 'Draft',
  Registration = 'Registration',
  InProgress = 'InProgress',
  Completed = 'Completed',
  Cancelled = 'Cancelled',
}
