/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TournamentPlayerDto {
  gamesPlayed?: number | string;
  id?: string;
  playerId?: string;
  playerName?: string;
  rating?: number | string | null;
  totalScore?: number | string;
}
