/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimeControl } from '../models/time-control';
import { TournamentFormat } from '../models/tournament-format';
export interface TournamentSettingsDto {
  allowByes?: boolean;
  entryFee?: number | string;
  format?: TournamentFormat;
  incrementInSeconds?: number | string;
  maxPlayers?: number | string;
  minPlayers?: number | string;
  numberOfRounds?: number | string;
  timeControl?: TimeControl;
  timeInMinutes?: number | string;
}
