/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePlayerProfileCommand {
  avatarUrl?: string | null;
  bio?: string | null;
  country?: string | null;
  dateOfBirth?: string | null;
  firstName: string;
  lastName: string;
  playerId: string;
}
