/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { PlayersService } from './services/players.service';
export { TournamentRequestsService } from './services/tournament-requests.service';
export { TournamentsService } from './services/tournaments.service';
export { MatchesService } from './services/matches.service';
