// <auto-generated />
using System;
using ChessTournaments.Modules.Tournaments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessTournaments.Modules.Tournaments.Infrastructure.Migrations
{
    [DbContext(typeof(TournamentsDbContext))]
    [Migration("20251231114344_UpdateTournamentSchema")]
    partial class UpdateTournamentSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Tournaments")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChessTournaments.Modules.Tournaments.Domain.Rounds.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("Rounds", "Tournaments");
                });

            modelBuilder.Entity("ChessTournaments.Modules.Tournaments.Domain.TournamentPlayers.TournamentPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "PlayerId")
                        .IsUnique();

                    b.ToTable("TournamentPlayers", "Tournaments");
                });

            modelBuilder.Entity("ChessTournaments.Modules.Tournaments.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.ToTable("Tournaments", "Tournaments");
                });

            modelBuilder.Entity("ChessTournaments.Modules.Tournaments.Domain.Rounds.Round", b =>
                {
                    b.HasOne("ChessTournaments.Modules.Tournaments.Domain.Tournaments.Tournament", null)
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ChessTournaments.Modules.Tournaments.Domain.Rounds.RoundMatch", "MatchReferences", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BoardNumber")
                                .HasColumnType("int");

                            b1.Property<bool>("IsCompleted")
                                .HasColumnType("bit");

                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("MatchId");

                            b1.HasIndex("RoundId");

                            b1.ToTable("RoundMatches", "Tournaments");

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.Navigation("MatchReferences");
                });

            modelBuilder.Entity("ChessTournaments.Modules.Tournaments.Domain.TournamentPlayers.TournamentPlayer", b =>
                {
                    b.HasOne("ChessTournaments.Modules.Tournaments.Domain.Tournaments.Tournament", null)
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ChessTournaments.Modules.Tournaments.Domain.TournamentPlayers.Score", "TotalScore", b1 =>
                        {
                            b1.Property<Guid>("TournamentPlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Points")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalScore");

                            b1.HasKey("TournamentPlayerId");

                            b1.ToTable("TournamentPlayers", "Tournaments");

                            b1.WithOwner()
                                .HasForeignKey("TournamentPlayerId");
                        });

                    b.Navigation("TotalScore")
                        .IsRequired();
                });

            modelBuilder.Entity("ChessTournaments.Modules.Tournaments.Domain.Tournaments.Tournament", b =>
                {
                    b.OwnsOne("ChessTournaments.Modules.Tournaments.Domain.Tournaments.TournamentSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("TournamentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AllowByes")
                                .HasColumnType("bit");

                            b1.Property<decimal>("EntryFee")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("IncrementInSeconds")
                                .HasColumnType("int");

                            b1.Property<int>("MaxPlayers")
                                .HasColumnType("int");

                            b1.Property<int>("MinPlayers")
                                .HasColumnType("int");

                            b1.Property<int>("NumberOfRounds")
                                .HasColumnType("int");

                            b1.Property<string>("TimeControl")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("TimeInMinutes")
                                .HasColumnType("int");

                            b1.HasKey("TournamentId");

                            b1.ToTable("Tournaments", "Tournaments");

                            b1.WithOwner()
                                .HasForeignKey("TournamentId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("ChessTournaments.Modules.Tournaments.Domain.Tournaments.Tournament", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
