/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addMatchTag } from '../fn/matches/add-match-tag';
import { AddMatchTag$Params } from '../fn/matches/add-match-tag';
import { createMatch } from '../fn/matches/create-match';
import { CreateMatch$Params } from '../fn/matches/create-match';
import { CreateMatchResponse } from '../models/create-match-response';
import { getMatchById } from '../fn/matches/get-match-by-id';
import { GetMatchById$Params } from '../fn/matches/get-match-by-id';
import { recordMatchResult } from '../fn/matches/record-match-result';
import { RecordMatchResult$Params } from '../fn/matches/record-match-result';
import { removeMatchTag } from '../fn/matches/remove-match-tag';
import { RemoveMatchTag$Params } from '../fn/matches/remove-match-tag';
import { searchMatches } from '../fn/matches/search-matches';
import { SearchMatches$Params } from '../fn/matches/search-matches';
import { TournamentMatchDto } from '../models/tournament-match-dto';
import { updateMatchMoves } from '../fn/matches/update-match-moves';
import { UpdateMatchMoves$Params } from '../fn/matches/update-match-moves';

@Injectable({ providedIn: 'root' })
export class MatchesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateMatchMoves()` */
  static readonly UpdateMatchMovesPath = '/api/matches/{matchId}/moves';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMatchMoves()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMatchMoves$Response(
    params: UpdateMatchMoves$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = updateMatchMoves(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMatchMoves$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMatchMoves(params: UpdateMatchMoves$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateMatchMoves$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }

  /** Path part for operation `searchMatches()` */
  static readonly SearchMatchesPath = '/api/matches/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchMatches()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchMatches$Response(
    params?: SearchMatches$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<TournamentMatchDto>>> {
    const obs = searchMatches(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchMatches$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchMatches(
    params?: SearchMatches$Params,
    context?: HttpContext,
  ): Observable<Array<TournamentMatchDto>> {
    const resp = this.searchMatches$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<TournamentMatchDto>>): Array<TournamentMatchDto> => r.body),
    );
  }

  /** Path part for operation `removeMatchTag()` */
  static readonly RemoveMatchTagPath = '/api/matches/{matchId}/tags/{tagName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeMatchTag()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeMatchTag$Response(
    params: RemoveMatchTag$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = removeMatchTag(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeMatchTag$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeMatchTag(params: RemoveMatchTag$Params, context?: HttpContext): Observable<void> {
    const resp = this.removeMatchTag$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }

  /** Path part for operation `recordMatchResult()` */
  static readonly RecordMatchResultPath = '/api/matches/{matchId}/result';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `recordMatchResult()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  recordMatchResult$Response(
    params: RecordMatchResult$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = recordMatchResult(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `recordMatchResult$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  recordMatchResult(params: RecordMatchResult$Params, context?: HttpContext): Observable<void> {
    const resp = this.recordMatchResult$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }

  /** Path part for operation `getMatchById()` */
  static readonly GetMatchByIdPath = '/api/matches/{matchId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMatchById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMatchById$Response(
    params: GetMatchById$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TournamentMatchDto>> {
    const obs = getMatchById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMatchById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMatchById(params: GetMatchById$Params, context?: HttpContext): Observable<TournamentMatchDto> {
    const resp = this.getMatchById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<TournamentMatchDto>): TournamentMatchDto => r.body),
    );
  }

  /** Path part for operation `createMatch()` */
  static readonly CreateMatchPath = '/api/matches';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createMatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMatch$Response(
    params: CreateMatch$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<CreateMatchResponse>> {
    const obs = createMatch(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createMatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createMatch(params: CreateMatch$Params, context?: HttpContext): Observable<CreateMatchResponse> {
    const resp = this.createMatch$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CreateMatchResponse>): CreateMatchResponse => r.body),
    );
  }

  /** Path part for operation `addMatchTag()` */
  static readonly AddMatchTagPath = '/api/matches/{matchId}/tags';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addMatchTag()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addMatchTag$Response(
    params: AddMatchTag$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = addMatchTag(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addMatchTag$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addMatchTag(params: AddMatchTag$Params, context?: HttpContext): Observable<void> {
    const resp = this.addMatchTag$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }
}
