/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AchievementResponse } from '../models/achievement-response';
import { apiPlayersPlayerIdPut } from '../fn/players/api-players-player-id-put';
import { ApiPlayersPlayerIdPut$Params } from '../fn/players/api-players-player-id-put';
import { apiPlayersPost } from '../fn/players/api-players-post';
import { ApiPlayersPost$Params } from '../fn/players/api-players-post';
import { apiPlayersTopGet } from '../fn/players/api-players-top-get';
import { ApiPlayersTopGet$Params } from '../fn/players/api-players-top-get';
import { apiPlayersUserUserIdGet } from '../fn/players/api-players-user-user-id-get';
import { ApiPlayersUserUserIdGet$Params } from '../fn/players/api-players-user-user-id-get';
import { getPlayerAchievements } from '../fn/players/get-player-achievements';
import { GetPlayerAchievements$Params } from '../fn/players/get-player-achievements';
import { PlayerDto } from '../models/player-dto';

@Injectable({ providedIn: 'root' })
export class PlayersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiPlayersPlayerIdPut()` */
  static readonly ApiPlayersPlayerIdPutPath = '/api/players/{playerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPlayersPlayerIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiPlayersPlayerIdPut$Response(
    params: ApiPlayersPlayerIdPut$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<PlayerDto>> {
    const obs = apiPlayersPlayerIdPut(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPlayersPlayerIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiPlayersPlayerIdPut(
    params: ApiPlayersPlayerIdPut$Params,
    context?: HttpContext,
  ): Observable<PlayerDto> {
    const resp = this.apiPlayersPlayerIdPut$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PlayerDto>): PlayerDto => r.body));
  }

  /** Path part for operation `apiPlayersTopGet()` */
  static readonly ApiPlayersTopGetPath = '/api/players/top';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPlayersTopGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPlayersTopGet$Response(
    params: ApiPlayersTopGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<PlayerDto>>> {
    const obs = apiPlayersTopGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPlayersTopGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPlayersTopGet(
    params: ApiPlayersTopGet$Params,
    context?: HttpContext,
  ): Observable<Array<PlayerDto>> {
    const resp = this.apiPlayersTopGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<Array<PlayerDto>>): Array<PlayerDto> => r.body));
  }

  /** Path part for operation `apiPlayersUserUserIdGet()` */
  static readonly ApiPlayersUserUserIdGetPath = '/api/players/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPlayersUserUserIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPlayersUserUserIdGet$Response(
    params: ApiPlayersUserUserIdGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<PlayerDto>> {
    const obs = apiPlayersUserUserIdGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPlayersUserUserIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPlayersUserUserIdGet(
    params: ApiPlayersUserUserIdGet$Params,
    context?: HttpContext,
  ): Observable<PlayerDto> {
    const resp = this.apiPlayersUserUserIdGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PlayerDto>): PlayerDto => r.body));
  }

  /** Path part for operation `getPlayerAchievements()` */
  static readonly GetPlayerAchievementsPath = '/api/players/{playerId}/achievements';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPlayerAchievements()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlayerAchievements$Response(
    params: GetPlayerAchievements$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<AchievementResponse>>> {
    const obs = getPlayerAchievements(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPlayerAchievements$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlayerAchievements(
    params: GetPlayerAchievements$Params,
    context?: HttpContext,
  ): Observable<Array<AchievementResponse>> {
    const resp = this.getPlayerAchievements$Response(params, context);
    return resp.pipe(
      map(
        (r: StrictHttpResponse<Array<AchievementResponse>>): Array<AchievementResponse> => r.body,
      ),
    );
  }

  /** Path part for operation `apiPlayersPost()` */
  static readonly ApiPlayersPostPath = '/api/players';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPlayersPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiPlayersPost$Response(
    params: ApiPlayersPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<PlayerDto>> {
    const obs = apiPlayersPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPlayersPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiPlayersPost(params: ApiPlayersPost$Params, context?: HttpContext): Observable<PlayerDto> {
    const resp = this.apiPlayersPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PlayerDto>): PlayerDto => r.body));
  }
}
