/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTournamentsGet } from '../fn/tournaments/api-tournaments-get';
import { ApiTournamentsGet$Params } from '../fn/tournaments/api-tournaments-get';
import { apiTournamentsIdCancelPost } from '../fn/tournaments/api-tournaments-id-cancel-post';
import { ApiTournamentsIdCancelPost$Params } from '../fn/tournaments/api-tournaments-id-cancel-post';
import { apiTournamentsIdCloseRegistrationPost } from '../fn/tournaments/api-tournaments-id-close-registration-post';
import { ApiTournamentsIdCloseRegistrationPost$Params } from '../fn/tournaments/api-tournaments-id-close-registration-post';
import { apiTournamentsIdCompletePost } from '../fn/tournaments/api-tournaments-id-complete-post';
import { ApiTournamentsIdCompletePost$Params } from '../fn/tournaments/api-tournaments-id-complete-post';
import { apiTournamentsIdGet } from '../fn/tournaments/api-tournaments-id-get';
import { ApiTournamentsIdGet$Params } from '../fn/tournaments/api-tournaments-id-get';
import { apiTournamentsIdOpenRegistrationPost } from '../fn/tournaments/api-tournaments-id-open-registration-post';
import { ApiTournamentsIdOpenRegistrationPost$Params } from '../fn/tournaments/api-tournaments-id-open-registration-post';
import { apiTournamentsIdPlayersGet } from '../fn/tournaments/api-tournaments-id-players-get';
import { ApiTournamentsIdPlayersGet$Params } from '../fn/tournaments/api-tournaments-id-players-get';
import { apiTournamentsIdPut } from '../fn/tournaments/api-tournaments-id-put';
import { ApiTournamentsIdPut$Params } from '../fn/tournaments/api-tournaments-id-put';
import { apiTournamentsIdRoundsGet } from '../fn/tournaments/api-tournaments-id-rounds-get';
import { ApiTournamentsIdRoundsGet$Params } from '../fn/tournaments/api-tournaments-id-rounds-get';
import { apiTournamentsOrganizerOrganizerIdGet } from '../fn/tournaments/api-tournaments-organizer-organizer-id-get';
import { ApiTournamentsOrganizerOrganizerIdGet$Params } from '../fn/tournaments/api-tournaments-organizer-organizer-id-get';
import { apiTournamentsPost } from '../fn/tournaments/api-tournaments-post';
import { ApiTournamentsPost$Params } from '../fn/tournaments/api-tournaments-post';
import { apiTournamentsTournamentIdRoundsPost } from '../fn/tournaments/api-tournaments-tournament-id-rounds-post';
import { ApiTournamentsTournamentIdRoundsPost$Params } from '../fn/tournaments/api-tournaments-tournament-id-rounds-post';
import { apiTournamentsTournamentIdRoundsRoundIdCompletePost } from '../fn/tournaments/api-tournaments-tournament-id-rounds-round-id-complete-post';
import { ApiTournamentsTournamentIdRoundsRoundIdCompletePost$Params } from '../fn/tournaments/api-tournaments-tournament-id-rounds-round-id-complete-post';
import { RoundDto } from '../models/round-dto';
import { TournamentDto } from '../models/tournament-dto';
import { TournamentPlayerDto } from '../models/tournament-player-dto';

@Injectable({ providedIn: 'root' })
export class TournamentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTournamentsIdGet()` */
  static readonly ApiTournamentsIdGetPath = '/api/tournaments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdGet$Response(
    params: ApiTournamentsIdGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TournamentDto>> {
    const obs = apiTournamentsIdGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdGet(
    params: ApiTournamentsIdGet$Params,
    context?: HttpContext,
  ): Observable<TournamentDto> {
    const resp = this.apiTournamentsIdGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<TournamentDto>): TournamentDto => r.body));
  }

  /** Path part for operation `apiTournamentsIdPut()` */
  static readonly ApiTournamentsIdPutPath = '/api/tournaments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiTournamentsIdPut$Response(
    params: ApiTournamentsIdPut$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TournamentDto>> {
    const obs = apiTournamentsIdPut(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiTournamentsIdPut(
    params: ApiTournamentsIdPut$Params,
    context?: HttpContext,
  ): Observable<TournamentDto> {
    const resp = this.apiTournamentsIdPut$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<TournamentDto>): TournamentDto => r.body));
  }

  /** Path part for operation `apiTournamentsIdOpenRegistrationPost()` */
  static readonly ApiTournamentsIdOpenRegistrationPostPath =
    '/api/tournaments/{id}/open-registration';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsIdOpenRegistrationPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdOpenRegistrationPost$Response(
    params: ApiTournamentsIdOpenRegistrationPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = apiTournamentsIdOpenRegistrationPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsIdOpenRegistrationPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdOpenRegistrationPost(
    params: ApiTournamentsIdOpenRegistrationPost$Params,
    context?: HttpContext,
  ): Observable<void> {
    const resp = this.apiTournamentsIdOpenRegistrationPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }

  /** Path part for operation `apiTournamentsOrganizerOrganizerIdGet()` */
  static readonly ApiTournamentsOrganizerOrganizerIdGetPath =
    '/api/tournaments/organizer/{organizerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsOrganizerOrganizerIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsOrganizerOrganizerIdGet$Response(
    params: ApiTournamentsOrganizerOrganizerIdGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<TournamentDto>>> {
    const obs = apiTournamentsOrganizerOrganizerIdGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsOrganizerOrganizerIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsOrganizerOrganizerIdGet(
    params: ApiTournamentsOrganizerOrganizerIdGet$Params,
    context?: HttpContext,
  ): Observable<Array<TournamentDto>> {
    const resp = this.apiTournamentsOrganizerOrganizerIdGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<TournamentDto>>): Array<TournamentDto> => r.body),
    );
  }

  /** Path part for operation `apiTournamentsIdRoundsGet()` */
  static readonly ApiTournamentsIdRoundsGetPath = '/api/tournaments/{id}/rounds';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsIdRoundsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdRoundsGet$Response(
    params: ApiTournamentsIdRoundsGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<RoundDto>>> {
    const obs = apiTournamentsIdRoundsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsIdRoundsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdRoundsGet(
    params: ApiTournamentsIdRoundsGet$Params,
    context?: HttpContext,
  ): Observable<Array<RoundDto>> {
    const resp = this.apiTournamentsIdRoundsGet$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<Array<RoundDto>>): Array<RoundDto> => r.body));
  }

  /** Path part for operation `apiTournamentsIdPlayersGet()` */
  static readonly ApiTournamentsIdPlayersGetPath = '/api/tournaments/{id}/players';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsIdPlayersGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdPlayersGet$Response(
    params: ApiTournamentsIdPlayersGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<TournamentPlayerDto>>> {
    const obs = apiTournamentsIdPlayersGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsIdPlayersGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdPlayersGet(
    params: ApiTournamentsIdPlayersGet$Params,
    context?: HttpContext,
  ): Observable<Array<TournamentPlayerDto>> {
    const resp = this.apiTournamentsIdPlayersGet$Response(params, context);
    return resp.pipe(
      map(
        (r: StrictHttpResponse<Array<TournamentPlayerDto>>): Array<TournamentPlayerDto> => r.body,
      ),
    );
  }

  /** Path part for operation `apiTournamentsGet()` */
  static readonly ApiTournamentsGetPath = '/api/tournaments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsGet$Response(
    params?: ApiTournamentsGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<TournamentDto>>> {
    const obs = apiTournamentsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsGet(
    params?: ApiTournamentsGet$Params,
    context?: HttpContext,
  ): Observable<Array<TournamentDto>> {
    const resp = this.apiTournamentsGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<TournamentDto>>): Array<TournamentDto> => r.body),
    );
  }

  /** Path part for operation `apiTournamentsPost()` */
  static readonly ApiTournamentsPostPath = '/api/tournaments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiTournamentsPost$Response(
    params: ApiTournamentsPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TournamentDto>> {
    const obs = apiTournamentsPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiTournamentsPost(
    params: ApiTournamentsPost$Params,
    context?: HttpContext,
  ): Observable<TournamentDto> {
    const resp = this.apiTournamentsPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<TournamentDto>): TournamentDto => r.body));
  }

  /** Path part for operation `apiTournamentsTournamentIdRoundsPost()` */
  static readonly ApiTournamentsTournamentIdRoundsPostPath =
    '/api/tournaments/{tournamentId}/rounds';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsTournamentIdRoundsPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsTournamentIdRoundsPost$Response(
    params: ApiTournamentsTournamentIdRoundsPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<RoundDto>> {
    const obs = apiTournamentsTournamentIdRoundsPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsTournamentIdRoundsPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsTournamentIdRoundsPost(
    params: ApiTournamentsTournamentIdRoundsPost$Params,
    context?: HttpContext,
  ): Observable<RoundDto> {
    const resp = this.apiTournamentsTournamentIdRoundsPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<RoundDto>): RoundDto => r.body));
  }

  /** Path part for operation `apiTournamentsIdCompletePost()` */
  static readonly ApiTournamentsIdCompletePostPath = '/api/tournaments/{id}/complete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsIdCompletePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdCompletePost$Response(
    params: ApiTournamentsIdCompletePost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = apiTournamentsIdCompletePost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsIdCompletePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdCompletePost(
    params: ApiTournamentsIdCompletePost$Params,
    context?: HttpContext,
  ): Observable<void> {
    const resp = this.apiTournamentsIdCompletePost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }

  /** Path part for operation `apiTournamentsTournamentIdRoundsRoundIdCompletePost()` */
  static readonly ApiTournamentsTournamentIdRoundsRoundIdCompletePostPath =
    '/api/tournaments/{tournamentId}/rounds/{roundId}/complete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsTournamentIdRoundsRoundIdCompletePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsTournamentIdRoundsRoundIdCompletePost$Response(
    params: ApiTournamentsTournamentIdRoundsRoundIdCompletePost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = apiTournamentsTournamentIdRoundsRoundIdCompletePost(
      this.http,
      this.rootUrl,
      params,
      context,
    );
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsTournamentIdRoundsRoundIdCompletePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsTournamentIdRoundsRoundIdCompletePost(
    params: ApiTournamentsTournamentIdRoundsRoundIdCompletePost$Params,
    context?: HttpContext,
  ): Observable<void> {
    const resp = this.apiTournamentsTournamentIdRoundsRoundIdCompletePost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }

  /** Path part for operation `apiTournamentsIdCloseRegistrationPost()` */
  static readonly ApiTournamentsIdCloseRegistrationPostPath =
    '/api/tournaments/{id}/close-registration';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsIdCloseRegistrationPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdCloseRegistrationPost$Response(
    params: ApiTournamentsIdCloseRegistrationPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = apiTournamentsIdCloseRegistrationPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsIdCloseRegistrationPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdCloseRegistrationPost(
    params: ApiTournamentsIdCloseRegistrationPost$Params,
    context?: HttpContext,
  ): Observable<void> {
    const resp = this.apiTournamentsIdCloseRegistrationPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }

  /** Path part for operation `apiTournamentsIdCancelPost()` */
  static readonly ApiTournamentsIdCancelPostPath = '/api/tournaments/{id}/cancel';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentsIdCancelPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdCancelPost$Response(
    params: ApiTournamentsIdCancelPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<void>> {
    const obs = apiTournamentsIdCancelPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentsIdCancelPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentsIdCancelPost(
    params: ApiTournamentsIdCancelPost$Params,
    context?: HttpContext,
  ): Observable<void> {
    const resp = this.apiTournamentsIdCancelPost$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<void>): void => r.body));
  }
}
