/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTournamentRequestsGet } from '../fn/tournament-requests/api-tournament-requests-get';
import { ApiTournamentRequestsGet$Params } from '../fn/tournament-requests/api-tournament-requests-get';
import { apiTournamentRequestsMyRequestsGet } from '../fn/tournament-requests/api-tournament-requests-my-requests-get';
import { ApiTournamentRequestsMyRequestsGet$Params } from '../fn/tournament-requests/api-tournament-requests-my-requests-get';
import { apiTournamentRequestsPendingGet } from '../fn/tournament-requests/api-tournament-requests-pending-get';
import { ApiTournamentRequestsPendingGet$Params } from '../fn/tournament-requests/api-tournament-requests-pending-get';
import { apiTournamentRequestsPost } from '../fn/tournament-requests/api-tournament-requests-post';
import { ApiTournamentRequestsPost$Params } from '../fn/tournament-requests/api-tournament-requests-post';
import { apiTournamentRequestsRequestIdApprovePost } from '../fn/tournament-requests/api-tournament-requests-request-id-approve-post';
import { ApiTournamentRequestsRequestIdApprovePost$Params } from '../fn/tournament-requests/api-tournament-requests-request-id-approve-post';
import { apiTournamentRequestsRequestIdCancelPost } from '../fn/tournament-requests/api-tournament-requests-request-id-cancel-post';
import { ApiTournamentRequestsRequestIdCancelPost$Params } from '../fn/tournament-requests/api-tournament-requests-request-id-cancel-post';
import { apiTournamentRequestsRequestIdRejectPost } from '../fn/tournament-requests/api-tournament-requests-request-id-reject-post';
import { ApiTournamentRequestsRequestIdRejectPost$Params } from '../fn/tournament-requests/api-tournament-requests-request-id-reject-post';
import { TournamentRequestDto } from '../models/tournament-request-dto';

@Injectable({ providedIn: 'root' })
export class TournamentRequestsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTournamentRequestsRequestIdRejectPost()` */
  static readonly ApiTournamentRequestsRequestIdRejectPostPath =
    '/api/tournament-requests/{requestId}/reject';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentRequestsRequestIdRejectPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiTournamentRequestsRequestIdRejectPost$Response(
    params: ApiTournamentRequestsRequestIdRejectPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TournamentRequestDto>> {
    const obs = apiTournamentRequestsRequestIdRejectPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentRequestsRequestIdRejectPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiTournamentRequestsRequestIdRejectPost(
    params: ApiTournamentRequestsRequestIdRejectPost$Params,
    context?: HttpContext,
  ): Observable<TournamentRequestDto> {
    const resp = this.apiTournamentRequestsRequestIdRejectPost$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<TournamentRequestDto>): TournamentRequestDto => r.body),
    );
  }

  /** Path part for operation `apiTournamentRequestsMyRequestsGet()` */
  static readonly ApiTournamentRequestsMyRequestsGetPath = '/api/tournament-requests/my-requests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentRequestsMyRequestsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsMyRequestsGet$Response(
    params?: ApiTournamentRequestsMyRequestsGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<TournamentRequestDto>>> {
    const obs = apiTournamentRequestsMyRequestsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentRequestsMyRequestsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsMyRequestsGet(
    params?: ApiTournamentRequestsMyRequestsGet$Params,
    context?: HttpContext,
  ): Observable<Array<TournamentRequestDto>> {
    const resp = this.apiTournamentRequestsMyRequestsGet$Response(params, context);
    return resp.pipe(
      map(
        (r: StrictHttpResponse<Array<TournamentRequestDto>>): Array<TournamentRequestDto> => r.body,
      ),
    );
  }

  /** Path part for operation `apiTournamentRequestsPendingGet()` */
  static readonly ApiTournamentRequestsPendingGetPath = '/api/tournament-requests/pending';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentRequestsPendingGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsPendingGet$Response(
    params?: ApiTournamentRequestsPendingGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<TournamentRequestDto>>> {
    const obs = apiTournamentRequestsPendingGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentRequestsPendingGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsPendingGet(
    params?: ApiTournamentRequestsPendingGet$Params,
    context?: HttpContext,
  ): Observable<Array<TournamentRequestDto>> {
    const resp = this.apiTournamentRequestsPendingGet$Response(params, context);
    return resp.pipe(
      map(
        (r: StrictHttpResponse<Array<TournamentRequestDto>>): Array<TournamentRequestDto> => r.body,
      ),
    );
  }

  /** Path part for operation `apiTournamentRequestsGet()` */
  static readonly ApiTournamentRequestsGetPath = '/api/tournament-requests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentRequestsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsGet$Response(
    params?: ApiTournamentRequestsGet$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<Array<TournamentRequestDto>>> {
    const obs = apiTournamentRequestsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentRequestsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsGet(
    params?: ApiTournamentRequestsGet$Params,
    context?: HttpContext,
  ): Observable<Array<TournamentRequestDto>> {
    const resp = this.apiTournamentRequestsGet$Response(params, context);
    return resp.pipe(
      map(
        (r: StrictHttpResponse<Array<TournamentRequestDto>>): Array<TournamentRequestDto> => r.body,
      ),
    );
  }

  /** Path part for operation `apiTournamentRequestsPost()` */
  static readonly ApiTournamentRequestsPostPath = '/api/tournament-requests';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentRequestsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiTournamentRequestsPost$Response(
    params: ApiTournamentRequestsPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TournamentRequestDto>> {
    const obs = apiTournamentRequestsPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentRequestsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiTournamentRequestsPost(
    params: ApiTournamentRequestsPost$Params,
    context?: HttpContext,
  ): Observable<TournamentRequestDto> {
    const resp = this.apiTournamentRequestsPost$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<TournamentRequestDto>): TournamentRequestDto => r.body),
    );
  }

  /** Path part for operation `apiTournamentRequestsRequestIdCancelPost()` */
  static readonly ApiTournamentRequestsRequestIdCancelPostPath =
    '/api/tournament-requests/{requestId}/cancel';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentRequestsRequestIdCancelPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsRequestIdCancelPost$Response(
    params: ApiTournamentRequestsRequestIdCancelPost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TournamentRequestDto>> {
    const obs = apiTournamentRequestsRequestIdCancelPost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentRequestsRequestIdCancelPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsRequestIdCancelPost(
    params: ApiTournamentRequestsRequestIdCancelPost$Params,
    context?: HttpContext,
  ): Observable<TournamentRequestDto> {
    const resp = this.apiTournamentRequestsRequestIdCancelPost$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<TournamentRequestDto>): TournamentRequestDto => r.body),
    );
  }

  /** Path part for operation `apiTournamentRequestsRequestIdApprovePost()` */
  static readonly ApiTournamentRequestsRequestIdApprovePostPath =
    '/api/tournament-requests/{requestId}/approve';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTournamentRequestsRequestIdApprovePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsRequestIdApprovePost$Response(
    params: ApiTournamentRequestsRequestIdApprovePost$Params,
    context?: HttpContext,
  ): Observable<StrictHttpResponse<TournamentRequestDto>> {
    const obs = apiTournamentRequestsRequestIdApprovePost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTournamentRequestsRequestIdApprovePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTournamentRequestsRequestIdApprovePost(
    params: ApiTournamentRequestsRequestIdApprovePost$Params,
    context?: HttpContext,
  ): Observable<TournamentRequestDto> {
    const resp = this.apiTournamentRequestsRequestIdApprovePost$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<TournamentRequestDto>): TournamentRequestDto => r.body),
    );
  }
}
