name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment (testing/staging/production)"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-${{ github.run_number }}
          path: dist/

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_FRONTEND_APP_TOKEN }}
          app_location: "dist/browser"
          output_location: "/"
          action: "upload"
